<a href="https://colab.research.google.com/github/JavZon/Takrorlash/blob/main/Untitled19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [23]:
df=pd.read_csv('/content/Train.csv')
df.head()

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1,Segmentation
0,462809,Male,No,22,No,Healthcare,1.0,Low,4.0,Cat_4,D
1,462643,Female,Yes,38,Yes,Engineer,NaN,Average,3.0,Cat_4,A
2,466315,Female,Yes,67,Yes,Engineer,1.0,Low,1.0,Cat_6,B
3,461735,Male,Yes,67,Yes,Lawyer,0.0,High,2.0,Cat_6,B
4,462669,Female,Yes,40,Yes,Entertainment,NaN,High,6.0,Cat_6,A

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8068 entries, 0 to 8067
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               8068 non-null   int64
 1   Gender           8068 non-null   object
 2   Ever_Married     7928 non-null   object
 3   Age              8068 non-null   int64
 4   Graduated        7990 non-null   object
 5   Profession       7944 non-null   object
 6   Work_Experience  7239 non-null   float64
 7   Spending_Score   8068 non-null   object
 8   Family_Size      7733 non-null   float64
 9   Var_1            7992 non-null   object
 10  Segmentation     8068 non-null   object
dtypes: float64(2), int64(2), object(7)
memory usage: 693.5+ KB

In [25]:
df['Var_1'].value_counts()

Var_1
Cat_6    5238
Cat_4    1089
Cat_3     822
Cat_2     422
Cat_7     203
Cat_1     133
Cat_5      85
Name: count, dtype: int64

In [27]:
df.drop(columns=['Var_1'], inplace=True)

In [28]:
df.isnull().sum()

ID                   0
Gender               0
Ever_Married       140
Age                  0
Graduated           78
Profession         124
Work_Experience    829
Spending_Score       0
Family_Size        335
Segmentation         0
dtype: int64

In [30]:
df.drop(columns=['ID'], inplace=True)

In [31]:
df.head()

,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Segmentation
0,Male,No,22,No,Healthcare,1.0,Low,4.0,D
1,Female,Yes,38,Yes,Engineer,NaN,Average,3.0,A
2,Female,Yes,67,Yes,Engineer,1.0,Low,1.0,B
3,Male,Yes,67,Yes,Lawyer,0.0,High,2.0,B
4,Female,Yes,40,Yes,Entertainment,NaN,High,6.0,A

In [32]:
df['Work_Experience'].value_counts()

Work_Experience
1.0     2354
0.0     2318
9.0      474
8.0      463
2.0      286
3.0      255
4.0      253
6.0      204
7.0      196
5.0      194
10.0      53
11.0      50
12.0      48
13.0      46
14.0      45
Name: count, dtype: int64

In [33]:
df['Profession'].value_counts()

Profession
Artist           2516
Healthcare       1332
Entertainment     949
Engineer          699
Doctor            688
Lawyer            623
Executive         599
Marketing         292
Homemaker         246
Name: count, dtype: int64

In [34]:
df.fillna(df.mean(), inplace=True)

TypeError: can only concatenate str (not "int") to str

In [35]:
from sklearn.preprocessing import LabelEncoder

In [37]:
df.sample(1)

,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Segmentation
2561,Male,No,59,Yes,Artist,1.0,Low,2.0,C

In [36]:
encoder=LabelEncoder()

In [38]:
df['Gender']=encoder.fit_transform(df['Gender'])
df['Ever_Married']=encoder.fit_transform(df['Ever_Married'])
df['Graduated']=encoder.fit_transform(df['Graduated'])
df['Profession']=encoder.fit_transform(df['Profession'])
df['Spending_Score']=encoder.fit_transform(df['Spending_Score'])
df['Segmentation']=encoder.fit_transform(df['Segmentation'])

In [39]:
df.head(1)

,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Segmentation
0,1,0,22,0,5,1.0,2,4.0,3

In [41]:
df.isnull().sum()

Gender               0
Ever_Married         0
Age                  0
Graduated            0
Profession           0
Work_Experience    829
Spending_Score       0
Family_Size        335
Segmentation         0
dtype: int64

In [42]:
df.fillna(df.mean(), inplace=True)

In [43]:
from sklearn.model_selection import train_test_split
from  sklearn.metrics import accuracy_score
from  sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler

In [44]:
df.head(2)

,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Segmentation
0,1,0,22,0,5,1.000000,2,4.0,3
1,0,1,38,1,2,2.641663,0,3.0,0

In [45]:
X=df.drop(columns=['Segmentation'])
y=df['Segmentation'].copy()

In [46]:
scaler=StandardScaler()
X=scaler.fit_transform(X)

In [47]:
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42)

In [48]:
X_train.shape, X_temp.shape, y_train.shape, y_temp.shape

((5647, 8), (2421, 8), (5647,), (2421,))

In [49]:
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

In [50]:
print(X_val.shape, X_test.shape, y_val.shape, y_test.shape)

(1210, 8) (1211, 8) (1210,) (1211,)

In [51]:
rf_model=RandomForestClassifier()
rf_model.fit(X_train, y_train)

RandomForestClassifier()

In [52]:
y_val_pred=rf_model.predict(X_val)

print(accuracy_score(y_val, y_val_pred))
print(confusion_matrix(y_val, y_val_pred))

0.4768595041322314
[[107  75  41  71]
 [ 71 107  64  38]
 [ 35  82 140  37]
 [ 58  33  28 223]]

In [53]:
y_test_pred=rf_model.predict(X_test)

print(accuracy_score(y_test, y_test_pred))
print(confusion_matrix(y_test, y_test_pred))

0.5012386457473162
[[112  67  45  79]
 [ 68  87  84  33]
 [ 37  65 146  38]
 [ 50  24  14 262]]